version: '3'

networks:
  php-net:
    driver: bridge

volumes:
  mariadb_vol:

services:
  projeto-ipia:
    image: dlpires300/projeto-pi-ipia:v1
    ports:
      - 8080:80
    networks:
      - php-net
        
  mariadb1:
    image: mariadb
    networks:
      - php-net
    ports:
      - 3306:3306
    environment:
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=admin
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - mariadb_vol:/var/lib/mysql

#docker container run -d --network php-net --name mariadb1 -e MARIADB_USER=root -e MARIADB_PASSWORD=root -e MARIADB_ROOT_PASSWORD=root -v mariadb_vol:/var/lib/mysql mariadb

#docker container run -p "8080:8080" -d --network php-net --name projeto-ipia dlpires300/projeto-pi-ipia:v1