-- MySQL Script generated by MySQL Workbench
-- Sun Jun 13 11:01:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projeto_3_ipia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto_3_ipia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto_3_ipia` DEFAULT CHARACTER SET utf8 ;
USE `projeto_3_ipia` ;

-- -----------------------------------------------------
-- Table `projeto_3_ipia`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_3_ipia`.`Endereco` (
  `cod_endereco` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_endereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_3_ipia`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_3_ipia`.`Cliente` (
  `cod_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(45) NOT NULL,
  `cpf_cliente` VARCHAR(11) NOT NULL,
  `tel_cliente` VARCHAR(11) NOT NULL,
  `rg_cliente` VARCHAR(11) NOT NULL,
  `Endereco_codigo_endereco` INT NOT NULL,
  PRIMARY KEY (`cod_cliente`, `Endereco_codigo_endereco`),
  INDEX `fk_Cliente_Endereco_idx` (`Endereco_codigo_endereco` ASC),
  CONSTRAINT `fk_Cliente_Endereco`
    FOREIGN KEY (`Endereco_codigo_endereco`)
    REFERENCES `projeto_3_ipia`.`Endereco` (`cod_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_3_ipia`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_3_ipia`.`Funcionario` (
  `cod_func` INT NOT NULL AUTO_INCREMENT,
  `nome_func` VARCHAR(45) NOT NULL,
  `cpf_func` VARCHAR(11) NOT NULL,
  `tel_func` VARCHAR(11) NOT NULL,
  `rg_func` VARCHAR(11) NOT NULL,
  `usuario` VARCHAR(10) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `Endereco_codigo_endereco` INT NOT NULL,
  PRIMARY KEY (`cod_func`, `Endereco_codigo_endereco`),
  INDEX `fk_Cliente_Endereco_idx` (`Endereco_codigo_endereco` ASC),
  CONSTRAINT `fk_Cliente_Endereco0`
    FOREIGN KEY (`Endereco_codigo_endereco`)
    REFERENCES `projeto_3_ipia`.`Endereco` (`cod_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- INSERT ADMIN USER

INSERT INTO `projeto_3_ipia`.`endereco`
(`cod_endereco`,
`rua`,
`numero`,
`bairro`,
`cep`,
`cidade`,
`estado`)
VALUES
(1,
'Rua admin',
'112',
'Admin',
'13800000',
'Mogi-Mirim',
'SP');


INSERT INTO `projeto_3_ipia`.`funcionario`
(`cod_func`,
`nome_func`,
`cpf_func`,
`tel_func`,
`rg_func`,
`usuario`,
`senha`,
`cargo`,
`Endereco_codigo_endereco`)
VALUES
(1,
'Admin',
'12345678998',
'19994445566',
'5444455543',
'admin',
'admin',
'Administrador',
1);

-- -----------------------------------------------------
-- Table `projeto_3_ipia`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_3_ipia`.`Venda` (
  `cod_venda` INT NOT NULL AUTO_INCREMENT,
  `dt_venda` DATETIME NOT NULL,
  `vl_total` DOUBLE NOT NULL,
  `Cliente_cod_cliente` INT NOT NULL,
  `Funcionario_cod_func` INT NOT NULL,
  PRIMARY KEY (`cod_venda`, `Cliente_cod_cliente`, `Funcionario_cod_func`),
  INDEX `fk_Venda_Cliente1_idx` (`Cliente_cod_cliente` ASC),
  INDEX `fk_Venda_Funcionario1_idx` (`Funcionario_cod_func` ASC),
  CONSTRAINT `fk_Venda_Cliente1`
    FOREIGN KEY (`Cliente_cod_cliente`)
    REFERENCES `projeto_3_ipia`.`Cliente` (`cod_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Funcionario1`
    FOREIGN KEY (`Funcionario_cod_func`)
    REFERENCES `projeto_3_ipia`.`Funcionario` (`cod_func`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_3_ipia`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_3_ipia`.`Produto` (
  `cod_produto` INT NOT NULL AUTO_INCREMENT,
  `dsc_produto` VARCHAR(45) NOT NULL,
  `vl_unitario` DOUBLE NOT NULL,
  `estoque_min` INT NOT NULL,
  `estoque_max` INT NOT NULL,
  `un_medida` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`cod_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_3_ipia`.`ItemVenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_3_ipia`.`ItemVenda` (
  `Venda_cod_venda` INT NOT NULL,
  `Produto_cod_produto` INT NOT NULL,
  `qtd_item` DOUBLE NOT NULL,
  `un_medida` VARCHAR(5) NULL,
  PRIMARY KEY (`Venda_cod_venda`, `Produto_cod_produto`),
  INDEX `fk_Venda_has_Produto_Produto1_idx` (`Produto_cod_produto` ASC),
  INDEX `fk_Venda_has_Produto_Venda1_idx` (`Venda_cod_venda` ASC),
  CONSTRAINT `fk_Venda_has_Produto_Venda1`
    FOREIGN KEY (`Venda_cod_venda`)
    REFERENCES `projeto_3_ipia`.`Venda` (`cod_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_has_Produto_Produto1`
    FOREIGN KEY (`Produto_cod_produto`)
    REFERENCES `projeto_3_ipia`.`Produto` (`cod_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_3_ipia`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_3_ipia`.`Fornecedor` (
  `cod_fornecedor` INT NOT NULL AUTO_INCREMENT,
  `nm_fornecedor` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(45) NOT NULL,
  `Endereco_cod_endereco` INT NOT NULL,
  PRIMARY KEY (`cod_fornecedor`, `Endereco_cod_endereco`),
  INDEX `fk_Fornecedor_Endereco1_idx` (`Endereco_cod_endereco` ASC),
  CONSTRAINT `fk_Fornecedor_Endereco1`
    FOREIGN KEY (`Endereco_cod_endereco`)
    REFERENCES `projeto_3_ipia`.`Endereco` (`cod_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_3_ipia`.`Movimentacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_3_ipia`.`Movimentacao` (
  `cod_mov` INT NOT NULL AUTO_INCREMENT,
  `dt_mov` DATETIME NOT NULL,
  `qtd_produto` INT NOT NULL,
  `tipo_mov` TINYINT NOT NULL,
  `Funcionario_cod_func` INT NOT NULL,
  `Produto_cod_produto` INT NOT NULL,
  PRIMARY KEY (`cod_mov`, `Funcionario_cod_func`, `Produto_cod_produto`),
  INDEX `fk_Movimentacao_Funcionario1_idx` (`Funcionario_cod_func` ASC),
  INDEX `fk_Movimentacao_Produto1_idx` (`Produto_cod_produto` ASC),
  CONSTRAINT `fk_Movimentacao_Funcionario1`
    FOREIGN KEY (`Funcionario_cod_func`)
    REFERENCES `projeto_3_ipia`.`Funcionario` (`cod_func`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movimentacao_Produto1`
    FOREIGN KEY (`Produto_cod_produto`)
    REFERENCES `projeto_3_ipia`.`Produto` (`cod_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
